name: econ2024
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - statsmodels
  - seaborn
  - ipykernel
  - ipython
  - jinja2
  - plotly
  - pyyaml
  - jupyter
  - tabulate
prefix: /home/amarov/anaconda3/envs/econ2024
